#!/bin/bash

if [[ -z $1 ]]; then echo "exit 1: make sure to pass an input, it must be an integer value."; exit 1; fi


# Removing metadata and commas
grep -v "^#" "data.csv" | tr -d ',' > "data.txt"


echo 'Even numbers:' $(grep -oP '[02468]\b' data.txt | wc -w)


# Distinguishing entries
les=0; gre=0; thr=$(echo "100*sqrt(3)/2" | bc -l)
while read x y z _; do
	num=$(echo "sqrt($x^2 + $y^2 + $z^2)" | bc -l)
	if (( $(echo "$num < $thr" | bc -l) )); then ((les++))
	else ((gre++)); fi
done < data.txt

echo "Numbers lesser than $thr: $les"
echo "Numbers greater than $thr: $gre"


for i in $(seq 1 $1); do
	awk -v div=$i '{for (j=1; j<=NF; j++) $j /= div}1' data.txt | sed -e 's/,/./g' > data_$i.txt
done
